import type {NextConfig} from 'next';
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin();

const nextConfig: NextConfig = {
  output: 'standalone',

  // Django's URLs end in a slash. Next would otherwise 308 `/api/admin/x/` to
  // `/api/admin/x` before the rewrite runs, and Django's APPEND_SLASH does not
  // redirect POST -- so every write from the panel would break while reads
  // appeared to work.
  skipTrailingSlashRedirect: true,

  async rewrites() {
    // Safari — and only Safari — asks the site root for its home-screen icon by
    // name, walking `/apple-touch-icon.png`, `-precomposed.png` and several
    // `-<size>.png` variants. None of them is a file here, and the matcher below
    // skips anything containing a dot, so each one fell through to `/[locale]`,
    // which matches any single segment: the home page was rendered in full with
    // `locale = "apple-touch-icon.png"` before the layout's guard threw it away.
    // That page is `force-dynamic`, so nothing was cached and every probe cost
    // three uncached Django requests. Five probes per visit, on every iPhone.
    //
    // `beforeFiles` is load-bearing. A plain rewrite array is `afterFiles`,
    // which is checked after the filesystem but still before dynamic routes --
    // enough here, but only by accident of ordering. Running before the
    // filesystem says what this is: the icon Safari is looking for already
    // exists at `/apple-icon.png`, generated by Next from `src/app/apple-icon.png`.
    // Answering with it is what makes Safari stop asking.
    const appleTouchIcon = {
      source: '/:icon(apple-touch-icon[\\w-]*\\.png)',
      destination: '/apple-icon.png',
    };

    // The control panel signs in with Django's session cookie, which is
    // HttpOnly and SameSite, and the backend sets CORS_ALLOW_CREDENTIALS=False.
    // The browser therefore has to reach Django on the same origin as this app
    // or it can never send that cookie.
    //
    // Production already works that way -- Caddy routes assembly.uz/api/* to
    // Django and never reaches this rule. This exists so local development
    // behaves identically instead of failing in a way that only shows up once
    // the two services are on different ports.
    // The trailing slash on the destination is load-bearing. Next captures
    // `:path*` without one, so proxying it verbatim would hand Django
    // `/api/admin/session`, which APPEND_SLASH answers with a 301 back to the
    // same URL the browser already asked for -- a redirect loop. Every DRF
    // route here ends in a slash, so restoring it unconditionally is correct.
    const api = process.env.API_URL ?? 'http://127.0.0.1:8000';
    return {
      beforeFiles: [appleTouchIcon],
      afterFiles: [{source: '/api/admin/:path*', destination: `${api}/api/admin/:path*/`}],
      fallback: [],
    };
  },
};

export default withNextIntl(nextConfig);
